### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by DanteAndroid** [ByoxCode/DrawView#17]
```
java.lang.NullPointerException: Attempt to invoke virtual method 'float com.byox.drawview.utils.SerializablePaint.getStrokeWidth()' on a null object reference
	at com.byox.drawview.views.DrawView.onTouch(SourceFile:404)
	at android.view.View.dispatchTouchEvent(View.java:9316)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2559)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2252)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2565)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2266)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2565)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2266)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2565)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2266)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2565)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2266)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2565)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2266)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2565)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2266)
	at com.android.internal.policy.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2736)
	at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1781)
	at android.app.Activity.dispatchTouchEvent(Activity.java:2906)
	at com.dante.diary.base.BaseActivity.dispatchTouchEvent(SourceFile:132)
	at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(SourceFile:71)
	at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(SourceFile:71)
	at com.android.internal.policy.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:2691)
	at android.view.View.dispatchPointerEvent(View.java:9542)
	at android.view.ViewRootImpl$SmartisanosTouchFilter.filterForEdgeTouch(ViewRootImpl.java:8085)
	at android.view.ViewRootImpl$SmartisanosTouchFilter.access$1800(ViewRootImpl.java:7991)
	at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4620)
	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4482)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3958)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4011)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3977)
	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4103)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3985)
	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4160)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3958)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4011)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3977)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3985)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3958)
	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:6503)
	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:6444)
	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:6405)
	at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:6696)
	at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:185)
	at android.os.MessageQueue.nativePollOnce(Native Method)
	at android.os.MessageQueue.next(MessageQueue.java:323)
	at android.os.Looper.loop(Looper.java:135)
	at android.app.ActivityThread.main(ActivityThread.java:5547)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:935)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:726)
```
Just have log from user

**Comment by ByoxCode** [comment]
This is a null pointer exception and the only thing that cause it is that DrawView isn't initialized in the activity
