### ISSUE TITLE
DrawView Crash

### ISSUE THREAD

**Issue by yaochangliang159** [ByoxCode/DrawView#20]
when i use drawview setBackgroundImage() method,
this is code:
![qq 20171109221817](https://user-images.githubusercontent.com/13497352/32609842-f1c263f2-c59b-11e7-929d-e558d82f7f20.png)

and it can show background Image Successfully,But When I start to other activity,drawview crashed:

`java.lang.RuntimeException: Parcelable encountered IOException writing serializable object (name = com.byox.drawview.dictionaries.DrawMove)
                                                                                  at android.os.Parcel.writeSerializable(Parcel.java:1505)
                                                                                  at android.os.Parcel.writeValue(Parcel.java:1453)
                                                                                  at android.os.Parcel.writeArrayMapInternal(Parcel.java:702)
                                                                                  at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1412)
                                                                                  at android.os.Bundle.writeToParcel(Bundle.java:1133)
                                                                                  at android.os.Parcel.writeBundle(Parcel.java:742)
                                                                                  at android.os.Parcel.writeValue(Parcel.java:1371)
                                                                                  at android.os.Parcel.writeSparseArray(Parcel.java:830)
                                                                                  at android.os.Parcel.writeValue(Parcel.java:1405)
                                                                                  at android.os.Parcel.writeArrayMapInternal(Parcel.java:702)
                                                                                  at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1412)
                                                                                  at android.os.Bundle.writeToParcel(Bundle.java:1133)
                                                                                  at android.os.Parcel.writeBundle(Parcel.java:742)
                                                                                  at android.support.v4.app.FragmentState.writeToParcel(Fragment.java:156)
                                                                                  at android.os.Parcel.writeTypedArray(Parcel.java:1285)
                                                                                  at android.support.v4.app.FragmentManagerState.writeToParcel(FragmentManager.java:617)
                                                                                  at android.os.Parcel.writeParcelable(Parcel.java:1474)
                                                                                  at android.os.Parcel.writeValue(Parcel.java:1380)
                                                                                  at android.os.Parcel.writeArrayMapInternal(Parcel.java:702)
                                                                                  at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1412)
                                                                                  at android.os.Bundle.writeToParcel(Bundle.java:1133)
                                                                                  at android.os.Parcel.writeBundle(Parcel.java:742)
                                                                                  at android.support.v4.app.FragmentState.writeToParcel(Fragment.java:156)
                                                                                  at android.os.Parcel.writeTypedArray(Parcel.java:1285)
                                                                                  at android.support.v4.app.FragmentManagerState.writeToParcel(FragmentManager.java:617)
                                                                                  at android.os.Parcel.writeParcelable(Parcel.java:1474)
                                                                                  at android.os.Parcel.writeValue(Parcel.java:1380)
                                                                                  at android.os.Parcel.writeArrayMapInternal(Parcel.java:702)
                                                                                  at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1412)
                                                                                  at android.os.Bundle.writeToParcel(Bundle.java:1133)
                                                                                  at android.os.Parcel.writeBundle(Parcel.java:742)
                                                                                  at android.support.v4.app.FragmentState.writeToParcel(Fragment.java:156)
                                                                                  at android.os.Parcel.writeTypedArray(Parcel.java:1285)
                                                                                  at android.support.v4.app.FragmentManagerState.writeToParcel(FragmentManager.java:617)
                                                                                  at android.os.Parcel.writeParcelable(Parcel.java:1474)
                                                                                  at android.os.Parcel.writeValue(Parcel.java:1380)
                                                                                  at android.os.Parcel.writeArrayMapInternal(Parcel.java:702)
                                                                                  at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1412)
                                                                                  at android.os.Bundle.writeToParcel(Bundle.java:1133)
                                                                                  at android.os.Parcel.writeBundle(Parcel.java:742)
                                                                                  at android.app.ActivityManagerProxy.activityStopped(ActivityManagerNative.java:3629)
                                                                                  at android.app.ActivityThread$StopInfo.run(ActivityThread.java:4028)
                                                                                  at android.os.Handler.handleCallback(Handler.java:761)
                                                                                  at android.os.Handler.dispatchMessage(Handler.java:98)
                                                                                  at android.os.Looper.loop(Looper.java:156)
                                                                                  at android.app.ActivityThread.main(ActivityThread.java:6577)
                                                                                  at java.lang.reflect.Method.invoke(Native Method)
                                                                                  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:942)
                                                                                  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:832)
                                                                               Caused by: java.io.NotSerializableException: android.graphics.Matrix
                                                                                  at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1224)
                                                                                  at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1584)
                                                                                  at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1549)
                                                                                  at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1472)
                                                                                  at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1218)
                                                                                  at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:346)
                                                                                  at android.os.Parcel.writeSerializable(Parcel.java:1500)
                                                                                  at android.os.Parcel.writeValue(Parcel.java:1453) 
                                                                                  at android.os.Parcel.writeArrayMapInternal(Parcel.java:702) 
                                                                                  at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1412) 
                                                                                  at android.os.Bundle.writeToParcel(Bundle.java:1133) 
                                                                                  at android.os.Parcel.writeBundle(Parcel.java:742) 
                                                                                  at android.os.Parcel.writeValue(Parcel.java:1371) 
                                                                                  at android.os.Parcel.writeSparseArray(Parcel.java:830) 
                                                                                  at android.os.Parcel.writeValue(Parcel.java:1405) 
                                                                                  at android.os.Parcel.writeArrayMapInternal(Parcel.java:702) 
                                                                                  at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1412) 
                                                                                  at android.os.Bundle.writeToParcel(Bundle.java:1133) 
                                                                                  at android.os.Parcel.writeBundle(Parcel.java:742) 
                                                                                  at android.support.v4.app.FragmentState.writeToParcel(Fragment.java:156) 
                                                                                  at android.os.Parcel.writeTypedArray(Parcel.java:1285) 
                                                                                  at android.support.v4.app.FragmentManagerState.writeToParcel(FragmentManager.java:617) 
                                                                                  at android.os.Parcel.writeParcelable(Parcel.java:1474) 
                                                                                  at android.os.Parcel.writeValue(Parcel.java:1380) 
                                                                                  at android.os.Parcel.writeArrayMapInternal(Parcel.java:702) 
                                                                                  at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1412) 
                                                                                  at android.os.Bundle.writeToParcel(Bundle.java:1133) 
                                                                                  at android.os.Parcel.writeBundle(Parcel.java:742) 
                                                                                  at android.support.v4.app.FragmentState.writeToParcel(Fragment.java:156) 
                                                                                  at android.os.Parcel.writeTypedArray(Parcel.java:1285) 
                                                                                  at android.support.v4.app.FragmentManagerState.writeToParcel(FragmentManager.java:617) 
                                                                                  at android.os.Parcel.writeParcelable(Parcel.java:1474) 
                                                                                  at android.os.Parcel.writeValue(Parcel.java:1380) 
                                                                                  at android.os.Parcel.writeArrayMapInternal(Parcel.java:702) 
                                                                                  at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1412) 
                                                                                  at android.os.Bundle.writeToParcel(Bundle.java:1133) 
                                                                                  at android.os.Parcel.writeBundle(Parcel.java:742) 
                                                                                  at android.support.v4.app.FragmentState.writeToParcel(Fragment.java:156) 
                                                                                  at android.os.Parcel.writeTypedArray(Parcel.java:1285) 
                                                                                  at android.support.v4.app.FragmentManagerState.writeToParcel(FragmentManager.java:617) 
                                                                                  at android.os.Parcel.writeParcelable(Parcel.java:1474) 
                                                                                  at android.os.Parcel.writeValue(Parcel.java:1380) 
                                                                                  at android.os.Parcel.writeArrayMapInternal(Parcel.java:702) 
                                                                                  at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1412) 
                                                                                  at android.os.Bundle.writeToParcel(Bundle.java:1133) 
                                                                                  at android.os.Parcel.writeBundle(Parcel.java:742) 
                                                                                  at android.app.ActivityManagerProxy.activityStopped(ActivityManagerNative.java:3629) 
                                                                                  at android.app.ActivityThread$StopInfo.run(ActivityThread.java:4028) 
                                                                                  at android.os.Handler.handleCallback(Handler.java:761) 
                                                                                  at android.os.Handler.dispatchMessage(Handler.java:98) 
                                                                                  at android.os.Looper.loop(Looper.java:156) 
                                                                                  at android.app.ActivityThread.main(ActivityThread.java:6577) 
                                                                                  at java.lang.reflect.Method.invoke(Native Method) 
                                                                                  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:942) 
                                                                                  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:832) 
`

**Comment by yaochangliang159** [comment]
![qq 20171109222209](https://user-images.githubusercontent.com/13497352/32610038-84cd4716-c59c-11e7-8865-549f0c737ffb.png)
![qq 20171109222236](https://user-images.githubusercontent.com/13497352/32610039-850a200a-c59c-11e7-85b7-4f70aa9bae79.png)

**Comment by asugar** [comment]
I have same error,any way to workaround?

**Comment by yaochangliang159** [comment]
@asugar @sushantDhamanekar 
i have solved this problem
copy this class to your project
`public class MyMatrix extends Matrix implements Serializable {
}
`
and replace the "Matrix" all in the DrawView.class
just like this:
![tim 20180630084657](https://user-images.githubusercontent.com/13497352/42119779-6f7ab1de-7c42-11e8-8751-43dc96789022.png)

**Comment by sushantDhamanekar** [comment]
Thanks for the reply and solution.

**Comment by sushantDhamanekar** [comment]
There is one more issue. 
When image is pinch zoomed, I cant see borders of the image. Image gets cropped at edge.
Is there any solution for it?

**Comment by yaochangliang159** [comment]
i do not use zoom,so i have no solution.....

**Comment by ByoxCode** [comment]
@sushantDhamanekar for the first issue, I'm working on a major update for include an option to load images from url as background. And for the second issue... I add this to the review list

**Comment by ByoxCode** [comment]
Ready in 1.0.2-SNAPSHOT update
